<?php include('assets/inc/header.php'); ?>
<h3 class="mb-4">Calendar</h3>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Calendar</title>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="./assets/css/todays_classes.css">
</head>
<body>

<div class="calendar-container">
  <div class="calendar-header">
    <h2 id="bla">August 2025</h2>
  </div>

  <div class="calendar-grid" id="calendarGrid">
    <!-- Days will be generated by JS -->
  </div>

  <!-- <div class="class-list" id="classList">
    <p style="text-align:center; color:#6b7280;">Select a date to view classes</p>
  </div> -->
</div>

<script>
  const calendarGrid = document.getElementById('calendarGrid');
  const classList = document.getElementById('classList');
  const bla = document.getElementById('bla')

  // Example class data
  const classes = {
    // '2025-08-05': [
    //   { subject: 'Math', time: '8:00 AM - 9:00 AM', teacher: 'Mr. Smith' },
    //   { subject: 'English', time: '10:00 AM - 11:00 AM', teacher: 'Ms. Jane' }
    // ],
    // '2025-08-06': [
    //   { subject: 'Biology', time: '9:00 AM - 10:00 AM', teacher: 'Dr. Lee' }
    // ],
    // '2025-08-07': [
    //   { subject: 'Chemistry', time: '11:00 AM - 12:00 PM', teacher: 'Mrs. Patel' }
    // ]
  };


  
  const toda = new Date()
  const exMon = new Date(
    toda.getFullYear(),
    toda.getMonth(),
    toda.getDate()
  )

  const myMonth = exMon.getMonth()

  const months = ["January", "Febuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" ]
  
  const today = new Date(); // today's date
  const year = 2025;
  const month = myMonth; // Augus
  
  bla.innerHTML= months[myMonth]

  const daysInMonth = new Date(year, month + 1, 0).getDate();

  const weekdays = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
  weekdays.forEach(day => {
    const cell = document.createElement('div');
    cell.style.fontWeight = '600';
    cell.textContent = day;
    calendarGrid.appendChild(cell);
  });

  // Padding before month starts
  const firstDay = new Date(year, month, 1).getDay();
  for (let i = 0; i < firstDay; i++) {
    calendarGrid.appendChild(document.createElement('div'));
  }

  // Render days
  for (let day = 1; day <= daysInMonth; day++) {
    const cell = document.createElement('div');
    const dateStr = `${year}-${String(month + 1).padStart(2, '0')}-${String(day).padStart(2, '0')}`;

    cell.textContent = day;

    if (classes[dateStr]) {
      cell.classList.add('has-class');
    }

    if (day === today.getDate()) {
      cell.classList.add('today');
    }

    cell.addEventListener('click', () => {
      renderClasses(dateStr);
    });

    calendarGrid.appendChild(cell);
  }

  function renderClasses(dateStr) {
    classList.innerHTML = '';
    const dayClasses = classes[dateStr];

    if (!dayClasses) {
      classList.innerHTML = ``;
      return;
    }

    dayClasses.forEach(c => {
      const div = document.createElement('div');
      div.className = 'class-card';
      div.innerHTML = `
        <h4>${c.subject}</h4>
        <p><strong>Time:</strong> ${c.time}</p>
        <p><strong>Teacher:</strong> ${c.teacher}</p>
      `;
      classList.appendChild(div);
    });
  }
</script>

</body>
</html>


<?php include('assets/inc/footer.php'); ?>
